### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by jpillora** [toots/node-heroku#10]
Tried updating env variables and it failed.

Seems like this module adheres to:

https://api-docs.heroku.com/

Although:

> "This documentation is no longer supported, please refer to the platform API reference."
https://devcenter.heroku.com/articles/platform-api-reference

**Comment by toots** [comment]
Actually, just fixed the config vars API.. Better late than nothing right?

**Comment by jpillora** [comment]
I have no memory ever opening this issue lol though nice work +1
