### ISSUE TITLE
invalid JSON' for put_config_vars

### ISSUE THREAD

**Issue by d1b1** [toots/node-heroku#12]
put_config_vars gives an error.

client.put_config_vars('myapp', '{"FOO": "bar", "BAZ": "qux" }', function(err, configs) {
  console.log('err', err);
  res.status(200).json(data);
});

data: '{"id":"bad_request","error":"Provided data is invalid JSON."}' }

**Comment by toots** [comment]
Thanks for the report. It seems that JSON is the default now for request payloads. I have published version `0.2.0` which should fix this. Please not, however, that JSON encoding is done by the library so you call should be:

```
client.put_config_vars('myapp', {FOO: "bar", BAZ: "qux" }, function(err, configs) {
...
```
